version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - 5601:5601

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:7.16.2
    ports:
      - 5000:5000
    command: logstash -f /logstash_dir/logstash.conf
    volumes:
      - ./logstash/logstash_dir:/logstash_dir
    environment:
      LS_JAVA_OPTS: " -Xms512m -Xmx512m"
volumes:
  esdata1:
    driver: local
